root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/chat-server ./cmd/chat-server"
bin = "./tmp/chat-server"
include_ext = ["go"]
exclude_dir = ["tmp"]
delay = 1000
stop_on_error = true

[log]
time = true
